---
abstract: 'Parse and Write gitosis config files'
author:
  - 'Chris Prather  C<< <perigrin@cpan.org> >>'
build_requires:
  Test::More: 0.42
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Gitosis-Config
no_index:
  directory:
    - ex
    - inc
    - t
requires:
  Config::INI: 0.013
  Moose: 0.56
  MooseX::AttributeHelpers: 0.13
resources:
  license: http://dev.perl.org/licenses/
version: 0.0.2
